### ISSUE TITLE
ubuntu 20.04 LTS, python 2.6 compilation method gives  error with readline module

### ISSUE THREAD

**Issue by haze1986** [NOAA-PMEL/PyFerret#110]
pyferret
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/users/ansley/git/PyFerret/install/lib64/python2.6/site-packages/pyferret/__init__.py", line 43, in <module>
ImportError: No module named readline

can i check with is the best way to have the readline module? I already have libreadline-dev package

**Comment by josborne-noaa** [comment]
It looks to me like your installation is not configured correctly. I would recommend that you try reinstalling with conda or rebuilding.

For installation instructions, please see:
https://github.com/NOAA-PMEL/PyFerret
